### ISSUE TITLE
开启esp有很严重的掉帧，原185开启后84，下界帧数更低

### ISSUE THREAD

**Issue by AShortFilm** [xiaodo1337/Content-Warning-Cheat#3]

**Comment by xiaodo1337** [comment]
我同样碰到了帧数严重下降的问题，我在怀疑是否是BepinEx导致的问题？总之现在不清楚导致帧数大幅度下跌的主要原因，如果有人知道这是什么原因导致的，欢迎提交反馈

**Comment by AShortFilm** [comment]
我尝试删掉了esp功能，但掉帧依然很严重🤓

**Comment by xiaodo1337** [comment]
新的版本可能修复了你所描述的问题！请尝试v1.1版本！

**Comment by AShortFilm** [comment]
![IMG_20240420_155138.jpg](https://github.com/xiaodo1337/Content-Warning-Cheat/assets/138278476/8a1bdd27-b193-4591-994a-5d9f98d751c7)

依然掉帧严重qwq

**Comment by AShortFilm** [comment]
@xiaodo1337 我认为获取玩家列表可以改成手动刷新，虽然可能会麻烦一点，但我觉得这可以获得更好的fps

**Comment by AShortFilm** [comment]
> @xiaodo1337 我认为获取玩家列表可以改成手动刷新，虽然可能会麻烦一点，但我觉得这可以获得更好的fps

或者:public static Player[] players;

private static float timeLastUpdate = 0.0f;
private static float updateInterval = 3f; fps/updateInterval = timesUpdated in Second

GetLobbyPlayers()
{
timeLastUpdate += Time.deltaTime;
if (timeLastUpdate >= updateInterval)
{
//Get All players
timeLastUpdate = 0f;
}
}

**Comment by tslpy** [comment]
+1

**Comment by tslpy** [comment]
1 开始后帧数降低很多 没开始前就正常
2 顺便给怪物物品汉化一下 不然大部分都看不懂
3 还有怪物 不是房主生成出来别人看不见 这个也要修复一下
4 还有有时候进游戏后EPS会显示一堆怪物或者重复的人 
这些都是目前遇到的问题 快修复下吧 很影响体验
@xiaodo1337 @xiaodo1337 @xiaodo1337

**Comment by AShortFilm** [comment]
> 1 开始后帧数降低很多 没开始前就正常 2 顺便给怪物物品汉化一下 不然大部分都看不懂 3 还有怪物 不是房主生成出来，别人看不见 这个也要修复一下 4 还有有时候进游戏后EPS会显示一堆怪物或者重复的人 这些都是目前遇到的问题 快修复下吧 很影响体验

2 属于游戏问题，你不是主机权限不足（也许）

**Comment by AShortFilm** [comment]
> 1 开始后帧数降低很多 没开始前就正常 2 顺便给怪物物品汉化一下 不然大部分都看不懂 3 还有怪物 不是房主生成出来，别人看不见 这个也要修复一下 4 还有有时候进游戏后EPS会显示一堆怪物或者重复的人 这些都是目前遇到的问题 快修复下吧 很影响体验

4 重复的模型同属于实体，尽管它只在你的视角出现，esp绘制的是实体我认为区分哪些是错误的实体比较困难

**Comment by tslpy** [comment]
@xiaodo1337 更新下 看看能不能都修复下

**Comment by tslpy** [comment]
@xiaodo1337 @xiaodo1337 今晚能行吗

**Comment by tslpy** [comment]
@xiaodo1337 已经三连过了 给修复下这些小问题呗

**Comment by xiaodo1337** [comment]
> @xiaodo1337 已经三连过了 给修复下这些小问题呗

> @xiaodo1337 @xiaodo1337 今晚能行吗

> @xiaodo1337 更新下 看看能不能都修复下

@tslpy 
首先，Issues不是你投放垃圾话的地方 ，而是用于反馈问题的地方，你的垃圾话已经被我删除。
其次，这个项目我是在用爱发电，我没有义务挪用我必要的时间去给你更新，如果你需要快速更新的话，你可以使用你的钱赞助开发者来提高开发速度。

**Comment by xiaodo1337** [comment]
> 1 开始后帧数降低很多 没开始前就正常 2 顺便给怪物物品汉化一下 不然大部分都看不懂 3 还有怪物 不是房主生成出来别人看不见 这个也要修复一下 4 还有有时候进游戏后EPS会显示一堆怪物或者重复的人 这些都是目前遇到的问题 快修复下吧 很影响体验 @xiaodo1337 @xiaodo1337 @xiaodo1337

关于你说的第一个问题，已经在修复计划当中，请耐心等待下一个版本发布！
第二个问题关系到本地化问题，我暂时不想去汉化它，这个功能可能在未来会出现。如果你愿意，你可以fork此项目汉化后再向我的项目进行合并！
第三第四个问题 @AShortFilm 已经给出了详细的回答，第4个问题来自游戏本身bug，请等待游戏官方修复！

**Comment by tslpy** [comment]
666 给你提意见还要赞助呢  傻毕   外面搜了下原来那么多免费的    你这算个√⑧    
你不爱做有的是人做   傻毕玩意也不照照镜子自己做的一坨答辩还想搞赞助   咋不去招棺材赞助商给你马准备好后事用的棺材呢？
最tm恶心你们这种美名其曰要赞助的沙沟。
![3333](https://github.com/xiaodo1337/Content-Warning-Cheat/assets/99876564/d1959b1b-be1a-4a89-a4d8-dd517c6e1550)
![2222](https://github.com/xiaodo1337/Content-Warning-Cheat/assets/99876564/1a99d0ea-16c7-4e59-8441-1ddf453ae65d)
![1111](https://github.com/xiaodo1337/Content-Warning-Cheat/assets/99876564/5a42cec3-9fa4-4576-99b8-f4f4a1d2e495)

**Comment by tslpy** [comment]
@AShortFilm @xiaodo1337

**Comment by xiaodo1337** [comment]
@tslpy 
我从没有向任何人索要一分钱^^ 且赞助是可选的
从头到尾到尾只有你在那里意淫
如果你觉得这个项目不适合你，那你可以不用它，而不是在这里乱叫，这样只会显得你很弱智

**Comment by xiaodo1337** [comment]
> > @xiaodo1337 我认为获取玩家列表可以改成手动刷新，虽然可能会麻烦一点，但我觉得这可以获得更好的fps
> 
> 或者:public static Player[] players;
> 
> private static float timeLastUpdate = 0.0f; private static float updateInterval = 3f; fps/updateInterval = timesUpdated in Second
> 
> GetLobbyPlayers() { timeLastUpdate += Time.deltaTime; if (timeLastUpdate >= updateInterval) { //Get All players timeLastUpdate = 0f; } }

感谢您的指正！我忘记了玩家列表一直循环导致的性能下降！我已经在v1.2版本修复了该问题，你可以现在去Releases页面下载最新版本看一下！

**Comment by AShortFilm** [comment]
> ！

嗯....![IMG_20240421_094103.jpg](https://github.com/xiaodo1337/Content-Warning-Cheat/assets/138278476/4535cfbb-5f4d-4166-b051-83bccf88d990)

问题依然存在，但明显好了很多

**Comment by AShortFilm** [comment]
> > ！
> 
> 嗯....![IMG_20240421_094103.jpg](https://github.com/xiaodo1337/Content-Warning-Cheat/assets/138278476/4535cfbb-5f4d-4166-b051-83bccf88d990)
> 
> 问题依然存在，但明显好了很多

多人情景下掉帧依然严重，甚至42fps●▽●

**Comment by xiaodo1337** [comment]
v1.3版本已完全修复。
