### ISSUE TITLE
彩色的脸和名字能暂时关掉吗

### ISSUE THREAD

**Issue by procedureRen** [xiaodo1337/Content-Warning-Cheat#6]

**Comment by AShortFilm** [comment]
后续的版本可能会改为自定义，当前版本可以自己编译删掉GetChoosedPlayerCount函数

**Comment by SandZZZZZZ** [comment]
用什么软件编译

**Comment by AShortFilm** [comment]
> 用什么软件编译
> 

https://www.youtube.com/watch?v=EgIbwCnQ680&list=PL26N-PX3Yu34gZZORwE4NWDpNVqjoov2u

**Comment by zme70** [comment]
0x2000011，找到一个Class，不知道怎么删
